apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-flask
  ports:
    - port: 80
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
