# здесь лежат переменные, которые Helm будет подставлять в шаблоны
replicaCount: 2

image:
  repository: my-flask-app
  tag: "1.0"

service:
  nodePort: 30008 # другой порт, чтобы не путать с первой частью

message: "ШОК КОНТЕНТ!!!🔥🔥🔥 HELM ОБНОВИЛ РЕЛИЗ ДАУНТАЙМА!"
