worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    # ОБЩИЙ БЛОК: Принудительный редирект HTTP (80) на HTTPS (443)
    server {
        listen 80;
        server_name site1.local site2.local;
        
        # 301 редирект на https
        return 301 https://$host$request_uri;
    }

    # ВИРТУАЛЬНЫЙ ХОСТ 1: site1.local
    server {
        listen 443 ssl;
        server_name site1.local;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # Проксирование
        location / {
            proxy_pass http://app1:5000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Использование ALIAS для статики
        # Специально убрал слэш в location для демонстрации Path Traversal
        location /files { # так безопаснее👉: location /files/ {
            alias /var/www/static1/;
            # По умолчанию Nginx запрещает обзор директорий, включим для удобства:
            autoindex on; 
        }
    }

    # ВИРТУАЛЬНЫЙ ХОСТ 2: site2.local
    server {
        listen 443 ssl;
        server_name site2.local;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        location / {
            proxy_pass http://app2:5000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /assets/ {
            alias /var/www/static2/;
            autoindex on;
        }
    }
}
